- name: Deploy Next.js App
  hosts: web
  become: yes
  tasks:
    - name: Pull latest Docker image
      command: docker pull my-docker-registry.com/my-nextjs-app:latest

    - name: Stop existing container
      command: docker rm -f nextjs_container
      ignore_errors: yes

    - name: Run Next.js container
      command: >
        docker run -d --name nextjs_container
        -p 4948:3000
        my-docker-registry.com/my-nextjs-app:latest